"""
Validated verification for NS_X72 Round 65.

This script extends the Round 64 theorem by two viscosity decades:
  [1e-5,1e-4] with N=900
  [1e-6,1e-5] with N=2800.

The coefficient formulas below are exact pure-Python renderings of the
Q(K,n) expressions generated by the SHA-256 pinned Round 58 symbolic source.
The proof uses:
- arbitrary IEEE-double approximate inverses;
- outward mpmath interval evaluation of the exact coefficients;
- a banded a-posteriori residual bound with explicit IEEE gamma_k budgets;
- exact rational viscosity chunks;
- the Round 56 infinite-tail monotonic contraction theorem.

The infinite tail is not truncated as a proof step.
"""
from pathlib import Path
import csv, hashlib, math
from fractions import Fraction
import numpy as np
import mpmath as mp

OUT=Path("/mnt/data/NS_X72_Round65_ViscosityCertificate_2026-08-18.csv")

def sha256(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()

assert sha256("/mnt/data/verify_NS_X72_Round58_SmallViscosityEndpoint_2026-08-17.py") == "f12e920dd2f4c17cd43166ec437a50ff7804a5526e50f1a33cab8b7ef5fb806d"
assert sha256("/mnt/data/verify_NS_X72_Round56_RigorousAdjointTail_2026-08-17.py") == "0dd1549c7b1f39f6915b172124d038890a10d84bd7802516b82083239010414d"
assert sha256("/mnt/data/verify_NS_X72_Round64_ValidatedViscosityHalfLine_2026-08-18.py") == "42ebf2bf79e40b7d8cc0a1fc341a3e49a545f091b7aef5412c1f2022c2d87a67"

def A_m2(K,n):
    return -K**3*(K**4 + 2*K**2*n**2 + 6*K**2*n - 13*K**2 + n**4 + 6*n**3 - 14*n**2 + 3*n + 4)/((K**2 + n**2)*(K**2 + n**2 - 4*n + 4)*(K**2 + n**2 - 2*n + 1))

def A0(K,n):
    return K*n*(K**10 + 8*K**8*n**2 + 30*K**8*n + 19*K**8 + 22*K**6*n**4 + 134*K**6*n**3 + 270*K**6*n**2 + 241*K**6*n + 83*K**6 + 28*K**4*n**6 + 222*K**4*n**5 + 663*K**4*n**4 + 946*K**4*n**3 + 604*K**4*n**2 + 122*K**4*n - K**4 + 17*K**2*n**8 + 162*K**2*n**7 + 592*K**2*n**6 + 1005*K**2*n**5 + 515*K**2*n**4 - 1000*K**2*n**3 - 1970*K**2*n**2 - 1319*K**2*n - 306*K**2 + 4*n**10 + 44*n**9 + 180*n**8 + 300*n**7 + 12*n**6 - 588*n**5 - 580*n**4 + 100*n**3 + 384*n**2 + 144*n)/((K**2 + n**2)*(n + 2)*(K**2 + n**2 - 2*n + 1)*(K**2 + n**2 + 4*n + 4)*(K**4 + 2*K**2*n**2 + 8*K**2*n + 4*K**2 + n**4 + 8*n**3 + 22*n**2 + 24*n + 9))

def A2(K,n):
    return K*(K**10 + 8*K**8*n**2 + 2*K**8*n - 9*K**8 + 22*K**6*n**4 + 42*K**6*n**3 - 6*K**6*n**2 - 65*K**6*n - 39*K**6 + 28*K**4*n**6 + 114*K**4*n**5 + 123*K**4*n**4 - 42*K**4*n**3 - 200*K**4*n**2 - 226*K**4*n - 101*K**4 + 17*K**2*n**8 + 110*K**2*n**7 + 228*K**2*n**6 + 107*K**2*n**5 - 335*K**2*n**4 - 616*K**2*n**3 - 330*K**2*n**2 + 15*K**2*n + 36*K**2 + 4*n**10 + 36*n**9 + 108*n**8 + 84*n**7 - 156*n**6 - 276*n**5 - 28*n**4 + 156*n**3 + 72*n**2)/((K**2 + n**2)*(K**2 + n**2 - 2*n + 1)*(K**2 + n**2 + 4*n + 4)*(K**4 + 2*K**2*n**2 + 8*K**2*n + 4*K**2 + n**4 + 8*n**3 + 22*n**2 + 24*n + 9))

def A4(K,n):
    return -K**3*n*(K**4 + 2*K**2*n**2 - 4*K**2 + n**4 - 2*n**2 + 1)*(K**4 + 2*K**2*n**2 + 2*K**2*n - 17*K**2 + n**4 + 2*n**3 - 26*n**2 - 99*n - 90)/((n + 2)*(K**2 + n**2 - 2*n + 1)*(K**2 + n**2 + 4*n + 4)*(K**2 + n**2 + 8*n + 16)*(K**4 + 2*K**2*n**2 + 8*K**2*n + 4*K**2 + n**4 + 8*n**3 + 22*n**2 + 24*n + 9))

def bcoef(K,n):
    return -16*n*(n + 1)*(K**4 + 2*K**2*n**2 - 4*K**2 + n**4 - 2*n**2 + 1)/((K**2 + n**2 - 2*n + 1)*(K**2 + n**2 + 2*n + 1))

AFUN={-2:A_m2,0:A0,2:A2,4:A4}
fibres=[("minus",math.sqrt(17)-3),("plus",math.sqrt(17)+3)]

mp.iv.dps=45

def gamma(k):
    u=2.0**-53
    return (k*u)/(1-k*u)

def up(x, rel=2e-12):
    return float(np.nextafter(float(x)*(1+rel)+1e-300, np.inf))

def K_iv(name):
    return mp.iv.sqrt(17)-3 if name=="minus" else mp.iv.sqrt(17)+3

def midrad(x):
    lo=np.nextafter(float(x.a),-np.inf)
    hi=np.nextafter(float(x.b),np.inf)
    mid=(lo+hi)/2.0
    return mid,(hi-lo)/2.0+abs(mid)*4e-16+1e-300

def precompute(name,Kv,N):
    m=N-1
    M0=np.zeros((m,m),dtype=float)
    M1=np.zeros((m,m),dtype=float)
    rhs=np.zeros(m,dtype=float)
    base=[]; deriv=[]; centry=[]
    rhs_mid=np.zeros(m,dtype=float)
    rhs_rad=np.zeros(m,dtype=float)
    kvi=K_iv(name)

    def add_double(row,idx,c0,c1=0.0):
        if idx<0:
            kk=-idx; sg=(-1)**kk; idx=kk; c0*=sg; c1*=sg
        if idx==0:
            rhs[row]-=c0
        elif idx==1:
            pass
        elif 2<=idx<=N:
            M0[row,idx-2]+=c0
            M1[row,idx-2]+=c1

    def add_interval(row,idx,v0,v1=None):
        if v1 is None:
            v1=mp.iv.mpf([0,0])
        if idx<0:
            kk=-idx; sg=(-1)**kk; idx=kk; v0*=sg; v1*=sg
        if idx==0:
            md,rd=midrad(v0); rhs_mid[row]-=md; rhs_rad[row]+=rd
        elif idx==1:
            pass
        elif 2<=idx<=N:
            md,rd=midrad(v0); base.append((row,idx-2,md,rd))
            md1,rd1=midrad(v1)
            if abs(md1)+rd1>1e-280:
                deriv.append((row,idx-2,md1,rd1))
        elif N+1<=idx<=N+3:
            md,rd=midrad(v0); centry.append((row,idx-(N+1),md,rd))

    for row,n in enumerate(range(1,N)):
        am=float(A_m2(Kv,n)); a0=float(A0(Kv,n)); a2=float(A2(Kv,n)); a4=float(A4(Kv,n)); bb=float(bcoef(Kv,n))
        add_double(row,n-2,-am); add_double(row,n,a0); add_double(row,n+1,0.0,-bb); add_double(row,n+2,-a2); add_double(row,n+4,a4)

        am=A_m2(kvi,n); a0=A0(kvi,n); a2=A2(kvi,n); a4=A4(kvi,n); bb=bcoef(kvi,n)
        add_interval(row,n-2,-am); add_interval(row,n,a0); add_interval(row,n+1,mp.iv.mpf([0,0]),-bb); add_interval(row,n+2,-a2); add_interval(row,n+4,a4)

    return dict(N=N,M0=M0,M1=M1,rhs=rhs,base=base,deriv=deriv,centry=centry,rhs_mid=rhs_mid,rhs_rad=rhs_rad,kvi=kvi)

def entries_at_center(data,center):
    cf=float(center)
    cerr=float(abs(Fraction.from_float(cf)-center))
    out=list(data["base"])
    for rr,cc,md,rd in data["deriv"]:
        val=cf*md
        rad=abs(cf)*rd+cerr*(abs(md)+rd)+abs(val)*4e-16+1e-300
        out.append((rr,cc,val,rad))
    return out

def inverse_residual_upper(R,entries,m):
    E=np.eye(m)
    radrow=np.zeros(m)
    absprod=np.zeros(m)
    for rr,cc,val,rad in entries:
        E[:,cc]-=R[:,rr]*val
        ar=np.abs(R[:,rr])
        radrow+=ar*rad
        absprod+=ar*(abs(val)+rad)
    obs=np.max(np.sum(np.abs(E),axis=1))*(1+gamma(m))
    radius=np.max(radrow)*(1+gamma(len(entries)))
    rounding=gamma(16)*np.max(absprod)*(1+gamma(len(entries)))
    return up(obs+radius+rounding+1e-14)

def solution_residual_upper(entries,rhs_mid,rhs_rad,x):
    res=rhs_mid.copy()
    rad=rhs_rad.copy()
    acc=np.abs(rhs_mid)+rhs_rad
    for rr,cc,val,vrad in entries:
        res[rr]-=val*x[cc]
        rad[rr]+=vrad*abs(x[cc])
        acc[rr]+=(abs(val)+vrad)*abs(x[cc])
    return up(np.max(np.abs(res)+rad+gamma(16)*acc)+1e-14)

def triangle_rows(R,entries):
    rows=np.zeros(R.shape[0])
    for rr,cc,val,rad in entries:
        rows+=np.abs(R[:,rr])*(abs(val)+rad)
    return np.nextafter(rows*(1+gamma(len(entries)))*(1+2e-12)+1e-300,np.inf)

def frac_iv(fr):
    return mp.iv.mpf(fr.numerator)/mp.iv.mpf(fr.denominator)

def q_upper(data,N,lo):
    K=data["kvi"]
    am=A_m2(K,N); a0=A0(K,N); a2=A2(K,N); a4=A4(K,N); bb=bcoef(K,N)
    q=(-am+a0+a2-a4)/(-frac_iv(lo)*bb)
    return up(float(abs(q).b))

def certify_chunk(data,name,lo,hi):
    N=data["N"]; m=N-1
    center=(lo+hi)/2; half=(hi-lo)/2
    cf=float(center); h=up(float(half))
    Mc=data["M0"]+cf*data["M1"]

    # Arbitrary approximate inverse and approximate core solution.
    R=np.linalg.inv(Mc)
    xt=R@data["rhs"]

    entries=entries_at_center(data,center)
    eta=inverse_residual_upper(R,entries,m)
    assert eta<1e-9

    Rnorm=up(np.max(np.sum(np.abs(R),axis=1))*(1+gamma(m)))
    rx=solution_residual_upper(entries,data["rhs_mid"],data["rhs_rad"],xt)
    errx=up(Rnorm/(1-eta)*rx)
    xinf=up(np.max(np.abs(xt))+errx)

    Brows=triangle_rows(R,data["deriv"])/(1-eta)
    rho=up(h*up(np.max(Brows)))
    assert rho<0.65

    Crows=triangle_rows(R,data["centry"])/(1-eta)
    Linf=up(np.max(Crows))

    def xb(row):
        return up(abs(xt[row])+errx+h*Brows[row]/(1-rho)*xinf)
    def lb(row):
        return up(Crows[row]+h*Brows[row]/(1-rho)*Linf)

    u3core=up(xt[1]+errx+h*Brows[1]/(1-rho)*xinf)
    Xbd=max(xb(-3),xb(-2),xb(-1))
    Lbd=max(lb(-3),lb(-2),lb(-1))
    L3=lb(1)

    qr=q_upper(data,N,lo)
    qh=up(qr*(1+Lbd))
    assert qh<0.80
    tail=up(qr*Xbd/(1-qh))
    u3=up(u3core+L3*tail)
    assert u3<0

    return dict(fibre=name,nu_lo=float(lo),nu_hi=float(hi),N=N,eta=eta,rho=rho,q_raw=qr,q_hat=qh,tail_bound=tail,u3_upper=u3,a3_lower=-u3)

def chunks(start,end):
    lo=start; out=[]
    while lo<end:
        hi=min(lo*Fraction(3,2),end)
        out.append((lo,hi)); lo=hi
    return out

ranges=[
    (Fraction(1,10**5),Fraction(1,10**4),900,"decade_1e-5"),
    (Fraction(1,10**6),Fraction(1,10**5),2800,"decade_1e-6"),
]
rows=[]
for name,Kv in fibres:
    for start,end,N,label in ranges:
        data=precompute(name,Kv,N)
        for lo,hi in chunks(start,end):
            cert=certify_chunk(data,name,lo,hi)
            cert["range"]=label
            rows.append(cert)

for name in ("minus","plus"):
    for label,threshold in [
        ("decade_1e-5",2.10e-5 if name=="minus" else 3.49e-5),
        ("decade_1e-6",2.08e-6 if name=="minus" else 3.46e-6),
    ]:
        worst=min(r["a3_lower"] for r in rows if r["fibre"]==name and r["range"]==label)
        assert worst>threshold

with OUT.open("w",newline="",encoding="utf-8") as f:
    fields=["range","fibre","nu_lo","nu_hi","N","eta","rho","q_raw","q_hat","tail_bound","u3_upper","a3_lower"]
    w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows(rows)

print("Round 65 validated verification passed.")
for name in ("minus","plus"):
    worst=min((r for r in rows if r["fibre"]==name),key=lambda r:r["a3_lower"])
    print(name,"worst new chunk =",worst)
print("Combined with pinned Round 64: a3(nu)>0 for both fibres and every nu>=1e-6.")
